# Generated by Django 2.1.1 on 2018-10-01 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('first', 'Первое блюдо'), ('second', 'Второе блюдо'), ('snack', 'Закуски'), ('dessert', 'Десерт'), ('salat', 'Салат'), ('drink', 'Напиток')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(choices=[('japan', 'Японская'), ('china', 'Китайская'), ('italia', 'Итальянская'), ('russian', 'Русская'), ('ukrainian', 'Украинская'), ('french', 'Французская'), ('usa', 'Американская'), ('european', 'Европейская'), ('asian', 'Азиатская'), ('african', 'Африканская')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('title', models.CharField(help_text='Enter the title of the article', max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID of recept', primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(help_text='Enter text of article')),
                ('photos', models.ImageField(help_text='Attach images', null=True, upload_to='')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Kind')),
                ('kitchen', models.ManyToManyField(help_text='Select a kitchen for this recept', to='catalog.Kitchen')),
            ],
        ),
    ]
