# Generated by Django 2.1.1 on 2018-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='photos',
            field=models.ImageField(help_text='Attach images', null=True, upload_to='static/img/blog-img'),
        ),
    ]
