# Generated by Django 2.1.2 on 2018-10-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='ingridients',
            field=models.TextField(default='', help_text='List and quantity of ingridients'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recept',
            name='photos',
            field=models.ImageField(help_text='Attach images', null=True, upload_to='static/img/blog-img'),
        ),
    ]
