# Generated by Django 2.1.2 on 2018-10-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='ingridients',
            field=models.CharField(blank=True, choices=[('meat', 'Мясо'), ('bird', 'Птица'), ('fish', 'Рыба'), ('sea', 'Морепродукты'), ('mashrooms', 'Грибы'), ('milk', 'Молочные продукты'), ('pasta', 'Макароны'), ('fructs', 'Фрукты'), ('vegetables', 'Овощи'), ('eggs', 'Яйца'), ('alcohol', 'Алкоголь')], max_length=15),
        ),
        migrations.AddField(
            model_name='recept',
            name='score',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(choices=[('first', 'Первое блюдо'), ('second', 'Второе блюдо'), ('snack', 'Закуски'), ('dessert', 'Десерт'), ('salat', 'Салат'), ('drink', 'Напиток'), ('breakfast', 'Завтрак'), ('garnish', 'Гарнир'), ('bake', 'Выпечка'), ('dough', 'Изделия из теста'), ('conservs', 'Консервы')], max_length=100),
        ),
    ]
