# Generated by Django 2.1.2 on 2018-10-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181009_1746'),
        ('catalog', '0002_auto_20181001_1103'),
    ]

    operations = [
    ]
