# Generated by Django 2.1.2 on 2018-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_20181009_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='ingridients',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='score',
        ),
        migrations.AddField(
            model_name='recept',
            name='Ingridients',
            field=models.TextField(default='', help_text='List and quantity of ingridients'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(choices=[('first', 'Первое блюдо'), ('second', 'Второе блюдо'), ('snack', 'Закуски'), ('dessert', 'Десерт'), ('salat', 'Салат'), ('drink', 'Напиток')], max_length=100),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
