# Generated by Django 2.1.1 on 2018-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180921_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen',
            field=models.CharField(help_text='Specify country for recept', max_length=100),
        ),
    ]
