# Generated by Django 2.1.2 on 2018-10-10 17:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pictures', models.ImageField(upload_to='static/img/articles')),
                ('text', models.TextField(help_text='Enter text of article')),
                ('current_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
