# Generated by Django 2.1.1 on 2018-09-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180921_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Choose kind of recept', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='recept',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Kind'),
        ),
        migrations.AlterField(
            model_name='recept',
            name='kitchen',
            field=models.ManyToManyField(help_text='Select a kitchen for this recept', to='catalog.Kitchen'),
        ),
    ]
