# Generated by Django 2.1.1 on 2018-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180921_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(choices=[('first', 'First'), ('drink', 'Drink')], help_text='Choose kind of recept', max_length=50),
        ),
    ]
