# Generated by Django 2.1.2 on 2018-10-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(choices=[('first', 'Первое блюдо'), ('second', 'Второе блюдо'), ('snack', 'Закуски'), ('dessert', 'Десерт'), ('salat', 'Салат'), ('drink', 'Напиток')], max_length=100, unique=True),
        ),
    ]
