# Generated by Django 2.1.1 on 2018-09-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180921_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='kitchen',
            field=models.CharField(choices=[('japan', 'Japanese'), ('china', 'China'), ('italia', 'Italiano'), ('europe', 'European'), ('unknown', 'Unknown')], max_length=100),
        ),
    ]
