# Generated by Django 2.1.1 on 2018-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180921_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(choices=[('first', 'First'), ('drink', 'Drink')], max_length=150),
        ),
    ]
