# Generated by Django 2.1.2 on 2018-10-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20181012_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='text_en',
            field=models.TextField(help_text='Enter text of article', null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='text_ru',
            field=models.TextField(help_text='Enter text of article', null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='text_uk',
            field=models.TextField(help_text='Enter text of article', null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='title_en',
            field=models.CharField(help_text='Enter the title of the article', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='title_ru',
            field=models.CharField(help_text='Enter the title of the article', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='title_uk',
            field=models.CharField(help_text='Enter the title of the article', max_length=200, null=True),
        ),
    ]
