# Generated by Django 2.1.1 on 2018-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180921_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='kind',
            field=models.CharField(choices=[('first', 'Первое блюдо'), ('second', 'Второе блюдо'), ('snack', 'Закуски'), ('dessert', 'Десерт'), ('salat', 'Салат'), ('drink', 'Напиток')], max_length=100),
        ),
    ]
