# Generated by Django 2.1.2 on 2018-10-16 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20181016_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=55)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=3000)),
                ('current_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='recept',
            name='kind_en',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='kind_ru',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='kind_uk',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='text_uk',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='title_uk',
        ),
    ]
