# Generated by Django 2.1.2 on 2018-10-16 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20181016_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='subject',
        ),
    ]
