# Generated by Django 2.1.2 on 2018-10-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='photos',
            field=models.ImageField(help_text='Attach images', null=True, upload_to='static/img/blog-img/<django.db.models.fields.UUIDField>'),
        ),
    ]
