# Generated by Django 2.1.2 on 2018-10-16 19:49

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20181016_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='preview_photo',
            field=models.ImageField(help_text='Attach image for preview 110x110', null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='recept',
            name='photos',
            field=models.ImageField(help_text='Attach image 1920x735', null=True, upload_to=catalog.models.upload_path_handler),
        ),
    ]
