# Generated by Django 2.1.2 on 2018-10-16 20:12

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20181016_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to=catalog.models.upload_path_handler)),
                ('image2', models.ImageField(null=True, upload_to=catalog.models.upload_path_handler)),
            ],
        ),
        migrations.AddField(
            model_name='recept',
            name='ph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ImageList'),
        ),
    ]
