# Generated by Django 2.1.2 on 2018-10-16 20:27

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20181016_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='title',
            field=models.CharField(help_text='Enter the title of the article', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='image1',
            field=models.ImageField(null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='image2',
            field=models.ImageField(null=True, upload_to=catalog.models.upload_path_handler),
        ),
    ]
