# Generated by Django 2.1.2 on 2018-10-16 20:35

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20181016_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelist',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='imagelist',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='preview_photo',
        ),
        migrations.AddField(
            model_name='imagelist',
            name='preview_image',
            field=models.ImageField(help_text='Preview image 110x110', null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='slider_image',
            field=models.ImageField(help_text='Slider image 1920x1280', null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='title_image1',
            field=models.ImageField(help_text='Title image 1920x735', null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='title_image2',
            field=models.ImageField(help_text='Title image 1920x735', null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='title_image3',
            field=models.ImageField(help_text='Title image 1920x735', null=True, upload_to=catalog.models.upload_path_handler),
        ),
    ]
