# Generated by Django 2.1.2 on 2018-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20181016_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='slider',
            field=models.BooleanField(default=False, help_text='Is field for slider?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pictures',
            field=models.ImageField(help_text='Image for article 900x300', upload_to='static/img/articles'),
        ),
    ]
