# Generated by Django 2.1.2 on 2018-10-17 09:17

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20181016_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='slider_image',
            field=models.ImageField(blank=True, help_text='Slider image 1920x1280', null=True, upload_to=catalog.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='imagelist',
            name='title_image3',
            field=models.ImageField(blank=True, help_text='Title image 1920x735', null=True, upload_to=catalog.models.upload_path_handler),
        ),
    ]
