# Generated by Django 2.1.2 on 2018-10-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20181017_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='cook_time',
            field=models.CharField(default='', help_text='Enter 3 digits separated by "$". Prepare time, cooking time, yields', max_length=20),
        ),
    ]
