# Generated by Django 2.1.2 on 2018-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_recept_cook_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(help_text='Enter text of article', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=models.TextField(help_text='Enter text of article', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ua',
            field=models.TextField(help_text='Enter text of article', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ua',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
