# Generated by Django 2.1.2 on 2018-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20181017_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', help_text='Tags separated bt comma', max_length=300),
        ),
        migrations.AddField(
            model_name='recept',
            name='tags',
            field=models.CharField(default='', help_text='Tags separated bt comma', max_length=300),
        ),
    ]
