# Generated by Django 2.1.2 on 2018-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20181017_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', help_text='Tags separated by comma', max_length=300),
        ),
    ]
