# Generated by Django 2.1.2 on 2018-10-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20181018_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='text_ua',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ua',
        ),
    ]
